repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 --statistics -j4
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy dgtools/
        language: system
        always_run: true
        pass_filenames: false
      - id: tests
        name: unit tests
        entry: python3 -m coverage run -m pytest test/
        language: system
        always_run: true
        pass_filenames: false
        verbose: false
      - id: coverage
        name: unit tests coverage report
        entry: python3 -m coverage report --omit=config*
        language: system
        always_run: true
        pass_filenames: false
        verbose: true
