name: Release
on:
  workflow_dispatch:
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Abort if not running on tag
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: exit 1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Python build requirements
        run: pip install -e '.[build]'
      - name: Run build
        run: python3 -m build .
      - name: Release python wheels from Framework
        uses: softprops/action-gh-release@v0.1.13
        with:
          fail_on_unmatched_files: true
          files: |
            ${{ github.workspace }}/dist/*.whl
